

version: 2.0
jobs:

    steps:
      - checkout


      - run:
          name: Make Executable
          command: |
            sudo chmod +x ./CxConsolePlugin-8.90.1/runCxConsole.sh
            ls -la ./CxConsolePlugin-8.90.1/runCxConsole.sh
            pwd
      - run:
          name: CxSAST Scan
          #######
          #command: sudo ./CxConsolePlugin-8.90.1/runCxConsole.sh Scan -v -CxServer "http://35.188.10.56" -projectName "graphql" -CxUser checkmarx -CxPassword B!gC0mmerce -Locationtype folder -LocationPath ~/repo -Preset "Checkmarx Default"
          #command: sudo ./CxConsolePlugin-8.90.1/runCxConsole.sh Scan -v -CxServer "http://35.188.10.56" -projectName "CxServer\graphql" -CxUser checkmarx -CxPassword SaO73X1VpFms#ffysY -Locationtype folder -LocationPath ~/repo -Preset "Checkmarx Default"
          command: sudo ./CxConsolePlugin-8.90.1/runCxConsole.sh Scan -v -CxServer http://35.188.10.56 -CxUser checkmarx -cxpassword XgL4AjxB37dc3wv# -ProjectName "CxServer\checkout-sdk-js" -Locationtype GIT -locationURL https://bc-venkata:6150e66a34d0ddf4b7dec5907469d565ca2e2643@github.com/bc-venkata/checkout-sdk-js -locationBranch refs/heads/master
